# Локальная база данных (MariaDB)
spring.datasource.url=jdbc:mariadb://localhost:9092/rembyte?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=${MARIADB_USERNAME}
spring.datasource.password=${MARIADB_PASSWORD}

# Для разработки удобно автоматически поддерживать схему
spring.jpa.hibernate.ddl-auto=update

# Локальная авторизация (пароли только через env)
fixbyte.admin.username=${FIXBYTE_ADMIN_USERNAME}
fixbyte.admin.password=${FIXBYTE_ADMIN_PASSWORD}
fixbyte.operator.username=${FIXBYTE_OPERATOR_USERNAME}
fixbyte.operator.password=${FIXBYTE_OPERATOR_PASSWORD}

